"""Initial migration for auth models and workout models

Revision ID: 51c2c1c94a66
Revises: 449bce97cff3
Create Date: 2024-07-31 23:38:19.685356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '51c2c1c94a66'
down_revision: Union[str, None] = '449bce97cff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workoutplans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workout_title', sa.String(), nullable=False),
    sa.Column('sub_heading', sa.String(), nullable=False),
    sa.Column('exercise_exp_level', sa.Enum('ROOKIE', 'BEGINNER', 'INTERMEDIATE', 'ADVANCE', 'BEAST', name='physicallevelenum'), nullable=False),
    sa.Column('plan_type', sa.Enum('DEFAULT', 'CUSTOM', name='workoutplantype'), nullable=False),
    sa.Column('total_workout_count', sa.Integer(), nullable=True),
    sa.Column('total_time', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('calories_burn', sa.Integer(), nullable=True),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workoutplans_id'), 'workoutplans', ['id'], unique=False)
    op.create_index(op.f('ix_workoutplans_sub_heading'), 'workoutplans', ['sub_heading'], unique=False)
    op.create_index(op.f('ix_workoutplans_workout_title'), 'workoutplans', ['workout_title'], unique=True)
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_muscle', sa.Enum('ABS', 'BACK', 'BICEPS', 'CARDIO', 'CHEST', 'LEGS', 'SHOULDERS', 'TRICEPS', name='exercisecategoryenum'), nullable=False),
    sa.Column('total_time', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('calories_burn', sa.Integer(), nullable=True),
    sa.Column('workout_plan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workout_plan'], ['workoutplans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_id'), 'workouts', ['id'], unique=False)
    op.create_index(op.f('ix_workouts_name'), 'workouts', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workouts_name'), table_name='workouts')
    op.drop_index(op.f('ix_workouts_id'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_index(op.f('ix_workoutplans_workout_title'), table_name='workoutplans')
    op.drop_index(op.f('ix_workoutplans_sub_heading'), table_name='workoutplans')
    op.drop_index(op.f('ix_workoutplans_id'), table_name='workoutplans')
    op.drop_table('workoutplans')
    # ### end Alembic commands ###
