"""added is active column in coach

Revision ID: 5753c7df580c
Revises: 51c2c1c94a66
Create Date: 2024-08-01 09:34:01.757532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5753c7df580c'
down_revision: Union[str, None] = '51c2c1c94a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coaches', 'is_active')
    # ### end Alembic commands ###
