"""added is_active in workout model

Revision ID: 9d341a9ce190
Revises: eada752fe913
Create Date: 2024-08-04 22:36:40.945420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d341a9ce190'
down_revision: Union[str, None] = 'eada752fe913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'is_active')
    # ### end Alembic commands ###
