"""changed name workout_plan to workout_plan_id in Workouts model

Revision ID: eada752fe913
Revises: 5753c7df580c
Create Date: 2024-08-01 23:09:59.847649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eada752fe913'
down_revision: Union[str, None] = '5753c7df580c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('workout_plan_id', sa.Integer(), nullable=False))
    op.drop_constraint('workouts_workout_plan_fkey', 'workouts', type_='foreignkey')
    op.create_foreign_key(None, 'workouts', 'workoutplans', ['workout_plan_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workouts', 'workout_plan')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('workout_plan', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workouts', type_='foreignkey')
    op.create_foreign_key('workouts_workout_plan_fkey', 'workouts', 'workoutplans', ['workout_plan'], ['id'], ondelete='CASCADE')
    op.drop_column('workouts', 'workout_plan_id')
    # ### end Alembic commands ###
